/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#004f54",
        "on-surface-variant": "#b9cacb",
        "on-surface": "#e2e0f7",
        "tertiary-container": "#e2d4ff",
        "secondary-container": "#6e06d0",
        "inverse-on-surface": "#2e2f40",
        "on-tertiary": "#3b0091",
        "surface-container-lowest": "#0c0d1c",
        "on-secondary": "#450086",
        "on-primary-container": "#006a71",
        "secondary-fixed": "#eddcff",
        "tertiary-fixed": "#e9ddff",
        "surface-variant": "#333344",
        "surface-container": "#1d1e2e",
        "on-tertiary-fixed-variant": "#5600ca",
        "outline": "#849495",
        "surface-tint": "#00dbe7",
        "on-tertiary-container": "#721aff",
        "surface-dim": "#111221",
        "surface": "#111221",
        "secondary": "#d8b9ff",
        "on-primary": "#00363a",
        "background": "#111221",
        "surface-container-low": "#191a2a",
        "on-secondary-fixed-variant": "#6200bc",
        "on-primary-fixed": "#002022",
        "tertiary": "#fcf5ff",
        "on-secondary-fixed": "#290055",
        "surface-container-highest": "#333344",
        "surface-bright": "#373849",
        "on-background": "#e2e0f7",
        "on-tertiary-fixed": "#23005c",
        "primary-fixed-dim": "#00dbe7",
        "on-error": "#690005",
        "secondary-fixed-dim": "#d8b9ff",
        "tertiary-fixed-dim": "#d0bcff",
        "inverse-primary": "#00696f",
        "inverse-surface": "#e2e0f7",
        "error": "#ffb4ab",
        "on-secondary-container": "#d5b5ff",
        "outline-variant": "#3a494b",
        "error-container": "#93000a",
        "surface-container-high": "#282939",
        "primary-container": "#00f2ff",
        "on-error-container": "#ffdad6",
        "primary": "#e1fdff",
        "primary-fixed": "#74f5ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin": "32px",
        "unit": "4px",
        "max_width": "1440px",
        "sm": "8px",
        "md": "16px",
        "xs": "4px",
        "lg": "24px",
        "xl": "48px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "h1": ["Space Grotesk", "sans-serif"],
        "h2": ["Space Grotesk", "sans-serif"],
        "h3": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "h1": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "h2": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h3": ["24px", { "lineHeight": "1.3", "letterSpacing": "0", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
